# Generated by Django 3.2.7 on 2022-05-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_event', models.ImageField(upload_to='static')),
                ('date_event', models.IntegerField()),
                ('month_event', models.TextField(max_length=20)),
                ('event_name', models.TextField(max_length=40)),
                ('description_event', models.TextField(max_length=100000)),
                ('event_coordinator', models.IntegerField()),
                ('register_link', models.TextField(max_length=20000)),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_gallery', models.ImageField(upload_to='static')),
                ('caption_gallery', models.TextField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_show', models.ImageField(upload_to='static')),
                ('show_name', models.TextField(max_length=40)),
                ('show_price', models.IntegerField()),
                ('time_show', models.IntegerField()),
                ('description_show', models.TextField(max_length=500)),
            ],
        ),
    ]
