# Generated by Django 3.2.7 on 2022-05-29 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0002_auto_20220528_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_detail',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='event_head',
            field=models.TextField(default='welcome'),
            preserve_default=False,
        ),
    ]
