# Generated by Django 3.2.7 on 2022-06-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0003_auto_20220529_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='first_prize',
            field=models.TextField(default='200'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='prize_pool',
            field=models.TextField(default='achu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='registration_prize',
            field=models.TextField(default='appu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='second_prize',
            field=models.TextField(default='nandhu'),
            preserve_default=False,
        ),
    ]
