# Generated by Django 3.2.7 on 2022-06-07 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yvidh', '0004_auto_20220607_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='rule1',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='rule2',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='rule3',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='rule4',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='rule5',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='rule6',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='rule7',
            field=models.TextField(default='hi'),
            preserve_default=False,
        ),
    ]
